# Generated by Django 5.2.1 on 2025-05-17 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse_postale', models.TextField(blank=True)),
                ('date_adhesion', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(choices=[('maladie', 'Maladie'), ('congé', 'Congé'), ('formation', 'Formation Externe'), ('familial', 'Raison Familiale'), ('autre', 'Autre')], max_length=50)),
                ('details_motif', models.TextField(blank=True)),
                ('certificat_medical', models.BooleanField(default=False)),
                ('notif_retour', models.BooleanField(default=False)),
                ('retour_verifie', models.BooleanField(default=False)),
                ('date_notification', models.DateField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
        migrations.CreateModel(
            name='DocumentRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('politique', 'Politique RH'), ('procedure', 'Procédure'), ('formulaire', 'Formulaire'), ('contrat', 'Contrat'), ('autre', 'Autre')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents_rh/')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('dernier_modif', models.DateField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('accessible_a', models.ManyToManyField(related_name='documents_accessibles', to='auth.group')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document RH',
                'verbose_name_plural': 'Documents RH',
            },
        ),
        migrations.CreateModel(
            name='ExclusionDemission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exclusion', 'Exclusion'), ('demission', 'Démission')], max_length=50)),
                ('date_effet', models.DateField()),
                ('motif', models.TextField()),
                ('document_reference', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents_exclusion/')),
                ('notes_additionnelles', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions_demissions', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusions_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exclusion ou Démission',
                'verbose_name_plural': 'Exclusions et Démissions',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('certification', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document_certification', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('technique', 'Compétence Technique'), ('soft', 'Soft Skill'), ('management', 'Management'), ('langue', 'Langue'), ('autre', 'Autre')], max_length=100)),
                ('niveau', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('date_acquisition', models.DateField(default='2023-01-01')),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='main.formation')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('description_changements', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='main.documentrh')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de document',
                'verbose_name_plural': 'Historique des documents',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.absence')),
                ('envoye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification de retour',
                'verbose_name_plural': 'Notifications de retour',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('date_nomination', models.DateField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('note', models.FloatField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)])),
                ('commentaires', models.TextField()),
                ('forces', models.TextField(blank=True)),
                ('axes_amelioration', models.TextField(blank=True)),
                ('objectifs', models.TextField()),
                ('objectifs_atteints', models.BooleanField(default=False)),
                ('date_prochain_suivi', models.DateField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='main.responsable')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
        migrations.CreateModel(
            name='ObjectifMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('status', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='non_commence', max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to=settings.AUTH_USER_MODEL)),
                ('responsable_suivi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_suivis', to='main.responsable')),
            ],
            options={
                'verbose_name': 'Objectif membre',
                'verbose_name_plural': 'Objectifs membres',
            },
        ),
    ]
